import React, { createContext, useState, useContext, useEffect } from 'react';

// Language Context for multilingual support
const LanguageContext = createContext();

// All translations for the entire application
const translations = {
  en: {
    navDashboard: 'Dashboard',
    navNodes: 'Edge Nodes',
    navAlerts: 'Alerts',
    navSettings: 'Settings',

    networkHealth: 'Network Health',
    systemStatus: 'System Status',
    activeNodes: 'Active Nodes',
    weeklyAlerts: 'Weekly Alerts',
    recentIncidents: 'Recent Incidents',
    liveTelemetry: 'Live Telemetry',

    activePerimeterNetwork: 'Active Perimeter Network',
    fetchingEdgeNodes: 'Fetching Edge Nodes...',
    threatLevel: 'Threat Level',
    status: 'Status',
    position: 'Position',
    ultrasonic: 'Ultrasonic',
    pirMotion: 'PIR Motion',
    microwaveRadar: 'Microwave Radar',
    secure: 'Secure',
    clear: 'Clear',
    detected: 'Detected',

    alertIntelligence: 'Alert Intelligence',
    comprehensiveThreatAnalytics: 'Comprehensive Threat Analytics',
    totalThreats: 'Total Threats',
    weeklyVolume: 'Weekly Volume',
    alertsInAWeek: 'Alerts in a Week',
    avgDuration: 'Avg Duration',
    timeBwAlerts: 'Time B/W Alerts',
    vulnerability: 'Vulnerability',
    mostAlertedNodes: 'Most Alerted Nodes',
    hits: 'Hits',
    liveFarmMap: 'Live Farm Map',
    realTimeNodeTelemetry: 'Real-Time Node Telemetry',

    profile: 'Profile',
    language: 'Language',
    importData: 'Import Data',
    statistics: 'Statistics',
    contactUs: 'Contact Us',
    about: 'About',
    guardianAvatar: 'Guardian Avatar',
    pickYourAvatar: 'Pick Your Avatar',
    chooseOneToGetStarted: 'Choose one to get started',
    displayName: 'Display Name',
    phoneNumber: 'Phone Number',
    emailAddress: 'Email Address',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    saved: 'Saved!',
    currentLanguage: 'Current Language',
    downloadCSV: 'Download .CSV / Excel',
    includesSensorData: 'Includes Sensor Data & Threat Events',
    version: 'Version',
    systemArchitecture: 'System Architecture',
    invalidPhone: 'Please enter a valid 10-digit phone number.',
    invalidEmail: 'Please enter a valid email address.',
  },
  hi: {
    navDashboard: 'डैशबोर्ड',
    navNodes: 'एज नोड्स',
    navAlerts: 'अलर्ट',
    navSettings: 'सेटिंग्स',

    networkHealth: 'नेटवर्क स्वास्थ्य',
    systemStatus: 'सिस्टम स्थिति',
    activeNodes: 'सक्रिय नोड्स',
    weeklyAlerts: 'साप्ताहिक अलर्ट',
    recentIncidents: 'हाल की घटनाएं',
    liveTelemetry: 'लाइव टेलीमेट्री',

    activePerimeterNetwork: 'सक्रिय परिधि नेटवर्क',
    fetchingEdgeNodes: 'एज नोड्स प्राप्त कर रहा है...',
    threatLevel: 'खतरे का स्तर',
    status: 'स्थिति',
    position: 'स्थिति (कोण)',
    ultrasonic: 'अल्ट्रासोनिक',
    pirMotion: 'पीआईआर मोशन',
    microwaveRadar: 'माइक्रोवेव रडार',
    secure: 'सुरक्षित',
    clear: 'स्पष्ट',
    detected: 'पता चला',

    alertIntelligence: 'अलर्ट इंटेलिजेंस',
    comprehensiveThreatAnalytics: 'व्यापक खतरे का विश्लेषण',
    totalThreats: 'कुल खतरे',
    weeklyVolume: 'साप्ताहिक मात्रा',
    alertsInAWeek: 'एक सप्ताह में अलर्ट',
    avgDuration: 'औसत अवधि',
    timeBwAlerts: 'अलर्ट के बीच का समय',
    vulnerability: 'भेद्यता',
    mostAlertedNodes: 'सर्वाधिक अलर्ट वाले नोड्स',
    hits: 'हिट्स',
    liveFarmMap: 'लाइव फार्म मैप',
    realTimeNodeTelemetry: 'रीयल-टाइम नोड टेलीमेट्री',

    profile: 'प्रोफ़ाइल',
    language: 'भाषा',
    importData: 'डेटा आयात करें',
    statistics: 'सांख्यिकी',
    contactUs: 'संपर्क करें',
    about: 'के बारे में',
    guardianAvatar: 'गार्जियन अवतार',
    pickYourAvatar: 'अपना अवतार चुनें',
    chooseOneToGetStarted: 'शुरू करने के लिए एक चुनें',
    displayName: 'प्रदर्शन नाम',
    phoneNumber: 'फ़ोन नंबर',
    emailAddress: 'ईमेल पता',
    saveChanges: 'परिवर्तन सहेजें',
    saving: 'सहेजा जा रहा है...',
    saved: 'सहेजा गया!',
    currentLanguage: 'वर्तमान भाषा',
    downloadCSV: 'डाउनलोड .CSV / Excel',
    includesSensorData: 'सेंसर डेटा और खतरे की घटनाएं शामिल हैं',
    version: 'संस्करण',
    systemArchitecture: 'सिस्टम आर्किटेक्चर',
    invalidPhone: 'कृपया एक वैध 10-अंकीय फ़ोन नंबर दर्ज करें।',
    invalidEmail: 'कृपया एक वैध ईमेल पता दर्ज करें।',
  },
  ta: {
    navDashboard: 'கட்டுப்பாட்டு அறை',
    navNodes: 'முனைப்புள்ளிகள்',
    navAlerts: 'எச்சரிக்கைகள்',
    navSettings: 'அமைப்புகள்',

    networkHealth: 'நெட்வொர்க் சுகாதாரம்',
    systemStatus: 'கணினி நிலை',
    activeNodes: 'செயலில் உள்ள முனைகள்',
    weeklyAlerts: 'வாராந்திர எச்சரிக்கைகள்',
    recentIncidents: 'சமீபத்திய நிகழ்வுகள்',
    liveTelemetry: 'நேரலை டெலிமெட்ரி',

    activePerimeterNetwork: 'செயலில் உள்ள சுற்றளவு நெட்வொர்க்',
    fetchingEdgeNodes: 'முனைப்புள்ளிகளைப் பெறுகிறது...',
    threatLevel: 'அச்சுறுத்தல் நிலை',
    status: 'நிலை',
    position: 'நிலை',
    ultrasonic: 'மீயொலி',
    pirMotion: 'பிஐஆர் இயக்கம்',
    microwaveRadar: 'மைக்ரோவேவ் ராடார்',
    secure: 'பாதுகாப்பானது',
    clear: 'தெளிவு',
    detected: 'கண்டறியப்பட்டது',

    alertIntelligence: 'எச்சரிக்கை நுண்ணறிவு',
    comprehensiveThreatAnalytics: 'விரிவான அச்சுறுத்தல் பகுப்பாய்வு',
    totalThreats: 'மொத்த அச்சுறுத்தல்கள்',
    weeklyVolume: 'வாராந்திர அளவு',
    alertsInAWeek: 'ஒரு வாரத்தில் எச்சரிக்கைகள்',
    avgDuration: 'சராசரி கால அளவு',
    timeBwAlerts: 'எச்சரிக்கைகளுக்கு இடையிலான நேரம்',
    vulnerability: 'பாதிப்பு',
    mostAlertedNodes: 'அதிக எச்சரிக்கப்பட்ட முனைகள்',
    hits: 'பதிவுகள்',
    liveFarmMap: 'நேரலை பண்ணை வரைபடம்',
    realTimeNodeTelemetry: 'நிகழ்நேர முனை டெலிமெட்ரி',

    profile: 'சுயவிவரம்',
    language: 'மொழி',
    importData: 'தரவை இறக்குமதி செய்',
    statistics: 'புள்ளியியல்',
    contactUs: 'தொடர்பு கொள்ள',
    about: 'பற்றி',
    guardianAvatar: 'பாதுகாவலர் அவதாரம்',
    pickYourAvatar: 'உங்கள் அவதாரத்தைத் தேர்ந்தெடுக்கவும்',
    chooseOneToGetStarted: 'தொடங்க ஒன்றைத் தேர்ந்தெடுக்கவும்',
    displayName: 'காட்சி பெயர்',
    phoneNumber: 'தொலைபேசி எண்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    saveChanges: 'மாற்றங்களை சேமிக்கவும்',
    saving: 'சேமிக்கிறது...',
    saved: 'சேமிக்கப்பட்டது!',
    currentLanguage: 'தற்போதைய மொழி',
    downloadCSV: 'பதிவிறக்கு .CSV / Excel',
    includesSensorData: 'சென்சார் தரவு & அச்சுறுத்தல் நிகழ்வுகள் அடங்கும்',
    version: 'பதிப்பு',
    systemArchitecture: 'கணினி கட்டமைப்பு',
    invalidPhone: 'செல்லுபடியாகும் 10 இலக்க தொலைபேசி எண்ணை உள்ளிடவும்.',
    invalidEmail: 'செல்லுபடியாகும் மின்னஞ்சல் முகவரியை உள்ளிடவும்.',
  },
  te: {
    navDashboard: 'డాష్‌బోర్డ్',
    navNodes: 'ఎడ్జ్ నోడ్స్',
    navAlerts: 'హెచ్చరికలు',
    navSettings: 'సెట్టింగ్‌లు',

    networkHealth: 'నెట్‌వర్క్ ఆరోగ్యం',
    systemStatus: 'సిస్టమ్ స్థితి',
    activeNodes: 'క్రియాశీల నోడ్స్',
    weeklyAlerts: 'వారపు హెచ్చరికలు',
    recentIncidents: 'ఇటీవలి సంఘటనలు',
    liveTelemetry: 'లైవ్ టెలిమెట్రీ',

    activePerimeterNetwork: 'క్రియాశీల చుట్టుకొలత నెట్‌వర్క్',
    fetchingEdgeNodes: 'ఎడ్జ్ నోడ్‌లను పొందుతోంది...',
    threatLevel: 'ముప్పు స్థాయి',
    status: 'స్థితి',
    position: 'స్థానం',
    ultrasonic: 'అల్ట్రాసోనిక్',
    pirMotion: 'పిఐఆర్ మోషన్',
    microwaveRadar: 'మైక్రోవేవ్ రాడార్',
    secure: 'సురక్షితం',
    clear: 'స్పష్టం',
    detected: 'కనుగొనబడింది',

    alertIntelligence: 'హెచ్చరిక ఇంటెలిజెన్స్',
    comprehensiveThreatAnalytics: 'సమగ్ర ముప్పు విశ్లేషణ',
    totalThreats: 'మొత్తం బెదిరింపులు',
    weeklyVolume: 'వారపు పరిమాణం',
    alertsInAWeek: 'ఒక వారంలో హెచ్చరికలు',
    avgDuration: 'సగటు వ్యవధి',
    timeBwAlerts: 'హెచ్చరికల మధ్య సమయం',
    vulnerability: 'దుర్బలత్వం',
    mostAlertedNodes: 'అత్యధికంగా హెచ్చరించబడిన నోడ్స్',
    hits: 'హిట్స్',
    liveFarmMap: 'లైవ్ ఫార్మ్ మ్యాప్',
    realTimeNodeTelemetry: 'రియల్ టైమ్ నోడ్ టెలిమెట్రీ',

    profile: 'ప్రొఫైల్',
    language: 'భాష',
    importData: 'డేటాను దిగుమతి చేయండి',
    statistics: 'గణాంకాలు',
    contactUs: 'మమ్మల్ని సంప్రదించండి',
    about: 'గురించి',
    guardianAvatar: 'గార్డియన్ అవతార్',
    pickYourAvatar: 'మీ అవతార్‌ను ఎంచుకోండి',
    chooseOneToGetStarted: 'ప్రారంభించడానికి ఒకదాన్ని ఎంచుకోండి',
    displayName: 'ప్రదర్శన పేరు',
    phoneNumber: 'ఫోన్ నంబర్',
    emailAddress: 'ఈమెయిల్ చిరునామా',
    saveChanges: 'మార్పులను సేవ్ చేయండి',
    saving: 'సేవ్ చేయబడుతోంది...',
    saved: 'సేవ్ చేయబడింది!',
    currentLanguage: 'ప్రస్తుత భాష',
    downloadCSV: '.CSV / Excel డౌన్‌లోడ్ చేయండి',
    includesSensorData: 'సెన్సార్ డేటా & థ్రెట్ ఈవెంట్‌లను కలిగి ఉంటుంది',
    version: 'వెర్షన్',
    systemArchitecture: 'సిస్టమ్ ఆర్కిటెక్చర్',
    invalidPhone: 'దయచేసి చెల్లుబాటు అయ్యే 10-అంకెల ఫోన్ నంబర్‌ను నమోదు చేయండి.',
    invalidEmail: 'దయచేసి చెల్లుబాటు అయ్యే ఇమెయిల్ చిరునామాను నమోదు చేయండి.',
  },
  mr: {
    navDashboard: 'डॅशबोर्ड',
    navNodes: 'एज नोड्स',
    navAlerts: 'अलर्ट',
    navSettings: 'सेटिंग्ज',

    networkHealth: 'नेटवर्क आरोग्य',
    systemStatus: 'सिस्टम स्थिती',
    activeNodes: 'सक्रिय नोड्स',
    weeklyAlerts: 'साप्ताहिक अलर्ट',
    recentIncidents: 'अलीकडील घटना',
    liveTelemetry: 'थेट टेलीमेट्री',

    activePerimeterNetwork: 'सक्रिय परिमिती नेटवर्क',
    fetchingEdgeNodes: 'एज नोड्स आणत आहे...',
    threatLevel: 'धोका पातळी',
    status: 'स्थिती',
    position: 'स्थिती',
    ultrasonic: 'अल्ट्रासोनिक',
    pirMotion: 'पीआयआर मोशन',
    microwaveRadar: 'मायक्रोवेव्ह रडार',
    secure: 'सुरक्षित',
    clear: 'स्पष्ट',
    detected: 'शोधले',

    alertIntelligence: 'अलर्ट इंटेलिजन्स',
    comprehensiveThreatAnalytics: 'सर्वसमावेशक धोका विश्लेषण',
    totalThreats: 'एकूण धोके',
    weeklyVolume: 'साप्ताहिक खंड',
    alertsInAWeek: 'एका आठवड्यात अलर्ट',
    avgDuration: 'सरासरी कालावधी',
    timeBwAlerts: 'अलर्टमधील वेळ',
    vulnerability: 'असुरक्षितता',
    mostAlertedNodes: 'सर्वाधिक अलर्ट केलेले नोड्स',
    hits: 'हिट्स',
    liveFarmMap: 'थेट फार्म नकाशा',
    realTimeNodeTelemetry: 'रिअल-टाइम नोड टेलीमेट्री',

    profile: 'प्रोफाइल',
    language: 'भाषा',
    importData: 'डेटा आयात करा',
    statistics: 'आकडेवारी',
    contactUs: 'आमच्याशी संपर्क साधा',
    about: 'बद्दल',
    guardianAvatar: 'गार्डियन अवतार',
    pickYourAvatar: 'तुमचा अवतार निवडा',
    chooseOneToGetStarted: 'प्रारंभ करण्यासाठी एक निवडा',
    displayName: 'प्रदर्शन नाव',
    phoneNumber: 'फोन नंबर',
    emailAddress: 'ईमेल पत्ता',
    saveChanges: 'बदल जतन करा',
    saving: 'जतन करत आहे...',
    saved: 'जतन केले!',
    currentLanguage: 'सध्याची भाषा',
    downloadCSV: 'डाउनलोड करा .CSV / Excel',
    includesSensorData: 'सेन्सर डेटा आणि धोका कार्यक्रम समाविष्ट आहेत',
    version: 'आवृत्ती',
    systemArchitecture: 'सिस्टम आर्किटेक्चर',
    invalidPhone: 'कृपया वैध 10-अंकी फोन नंबर प्रविष्ट करा.',
    invalidEmail: 'कृपया वैध ईमेल पत्ता प्रविष्ट करा.',
  },
  bn: {
    navDashboard: 'ড্যাশবোর্ড',
    navNodes: 'এজ নোডস',
    navAlerts: 'সতর্কতা',
    navSettings: 'সেটিংস',

    networkHealth: 'নেটওয়ার্ক স্বাস্থ্য',
    systemStatus: 'সিস্টেম স্ট্যাটাস',
    activeNodes: 'সক্রিয় নোডস',
    weeklyAlerts: 'সাপ্তাহিক সতর্কতা',
    recentIncidents: 'সাম্প্রতিক ঘটনা',
    liveTelemetry: 'লাইভ টেলিমেট্রি',

    activePerimeterNetwork: 'সক্রিয় পেরিমিটার নেটওয়ার্ক',
    fetchingEdgeNodes: 'এজ নোডস আনছে...',
    threatLevel: 'হুমকির স্তর',
    status: 'স্ট্যাটাস',
    position: 'অবস্থান',
    ultrasonic: 'আল্ট্রাসোনিক',
    pirMotion: 'পিআইআর মোশন',
    microwaveRadar: 'মাইক্রোওয়েভ রাডার',
    secure: 'নিরাপদ',
    clear: 'পরিষ্কার',
    detected: 'শনাক্ত করা হয়েছে',

    alertIntelligence: 'অ্যালার্ট ইন্টেলিজেন্স',
    comprehensiveThreatAnalytics: 'ব্যাপক থ্রেট অ্যানালিটিক্স',
    totalThreats: 'মোট হুমকি',
    weeklyVolume: 'সাপ্তাহিক ভলিউম',
    alertsInAWeek: 'এক সপ্তাহে সতর্কতা',
    avgDuration: 'গড় সময়কাল',
    timeBwAlerts: 'সতর্কতার মধ্যে সময়',
    vulnerability: 'দুর্বলতা',
    mostAlertedNodes: 'সর্বাধিক সতর্কিত নোডস',
    hits: 'হিট',
    liveFarmMap: 'লাইভ ফার্ম ম্যাপ',
    realTimeNodeTelemetry: 'রিয়েল-টাইম নোড টেলিমেট্রি',

    profile: 'প্রোফাইল',
    language: 'ভাষা',
    importData: 'ডেটা আমদানি করুন',
    statistics: 'পরিসংখ্যান',
    contactUs: 'যোগাযোগ করুন',
    about: 'সম্পর্কে',
    guardianAvatar: 'গার্ডিয়ান অবতার',
    pickYourAvatar: 'আপনার অবতার নির্বাচন করুন',
    chooseOneToGetStarted: 'শুরু করতে একটি নির্বাচন করুন',
    displayName: 'প্রদর্শন নাম',
    phoneNumber: 'ফোন নম্বর',
    emailAddress: 'ইমেইল ঠিকানা',
    saveChanges: 'পরিবর্তনগুলো সংরক্ষণ করুন',
    saving: 'সংরক্ষণ করা হচ্ছে...',
    saved: 'সংরক্ষিত!',
    currentLanguage: 'বর্তমান ভাষা',
    downloadCSV: 'ডাউনলোড করুন .CSV / Excel',
    includesSensorData: 'সেন্সর ডেটা এবং থ্রেট ইভেন্ট অন্তর্ভুক্ত',
    version: 'সংস্করণ',
    systemArchitecture: 'সিস্টেম আর্কিটেকচার',
    invalidPhone: 'দয়া করে একটি বৈধ 10-সংখ্যার ফোন নম্বর লিখুন।',
    invalidEmail: 'দয়া করে একটি বৈধ ইমেইল ঠিকানা লিখুন।',
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    // Read from cookies, default to 'en'
    const match = document.cookie.match(new RegExp('(^| )lang=([^;]+)'));
    if (match) return match[2];
    
    // Fallback to localStorage
    const saved = localStorage.getItem('lang');
    return saved || 'en';
  });

  useEffect(() => {
    // Save to cookies (expires in 1 year)
    document.cookie = `lang=${lang}; path=/; max-age=31536000`;
    localStorage.setItem('lang', lang);
  }, [lang]);

  // Translate function
  const t = (key) => {
    return translations[lang]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
